### ISSUE TITLE
error of perm-mnist

### ISSUE THREAD

**Issue by Damonly15** [aimagelab/mammoth#38] opened 2024-04-30 10:58 UTC
Hi

I think there might be an issues with the latest implementation of the perm-mnist dataset. I tried different models and i always end up getting accuracies of around 10%. Does anyone else have the same problem?

**Comment by loribonna** [comment] 2024-04-30 12:33
Hi @Damonly15, thank you for reaching out. 

Yes, I looked into it and the issue is the creation of the `Permutation` transform in `datasets/perm_mnist.py` (line 77).
Turns out that when having multiple dataloader workers (as it is the default now) we need to define the permutation *during initialization* (instead of at runtime as it is now in `datasets/transforms/permutation.py`). 

A fix will be merged shortly, for now you can just pass an additional argument to line 77 of `datasets/perm_mnist.py`:
`transform = transforms.Compose((transforms.ToTensor(), Permutation(np.prod(PermutedMNIST.SIZE))))`
and use it to initialize the transform in line 18 of `datasets/transforms/permutation.py`:
`self.perm = np.random.permutation(size)`

**Closed** 2024-04-30 23:05 UTC
Labels: bug
